version: '2.1'

services:

  selenoid:
    image: 'aerokube/selenoid:latest'
    volumes:
      - /var/lib/jenkins/workspace/test_job/myapp_tests/selenoid:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
    - 4444:4444
    command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "myapptests_default"]

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: pass
    image: 'percona:5.7'
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-ppass", "-h", "127.0.0.1"]
      timeout: 10s
      retries: 10

  prepare_db:
    image: 'prepare_mysql:latest'
    depends_on:
      mysql:
        condition: service_healthy

  vk_api:
    image: 'vk_api:latest'
    depends_on:
      prepare_db:
        condition: service_started

  myapp:
    image: 'myapp:latest'
    volumes:
      - /var/lib/jenkins/workspace/test_job/myapp_tests/conf:/tmp/conf
    ports:
      - 8888:8888
    depends_on:
      vk_api:
        condition: service_started
    entrypoint: ["/app/myapp", "--config=/tmp/conf"]

  tests:
    build: /var/lib/jenkins/workspace/test_job/myapp_tests/
    volumes:
    - /tmp/alluredir:/alluredir
    - /var/lib/jenkins/workspace/test_job/myapp_tests:/myapp_tests
    depends_on:
      myapp:
        condition: service_started
